import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import { Resend } from 'resend';

dotenv.config({ path: '.env.local' });

const supabase = createClient(process.env.VITE_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY); // Requires service role for admin emails

const resend = new Resend(process.env.RESEND_API_KEY || 're_RjGg4waG_8hFS6L1uWEECAsrk5pqk2n28');

// Helper to send Capacity Warning alerts to Admins via Resend
async function sendCapacityAlertEmail(adminEmail, rt) {
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';

  console.log(`[SERVERLESS CAPACITY] Sending low inventory warning to ${adminEmail} for RoomType #${rt.id}...`);

  const htmlContent = `
    <div style="background-color: #0f172a; color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; padding: 40px 20px; min-height: 100vh;">
      <div style="max-width: 600px; margin: 0 auto; background: rgba(30, 41, 59, 0.85); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 24px; padding: 40px; box-shadow: 0 20px 40px rgba(0, 0, 0, 0.35);">
        
        <!-- Header with Warning design -->
        <div style="background: linear-gradient(135deg, #ef4444 0%, #f97316 100%); border-radius: 16px; padding: 24px; text-align: center; margin-bottom: 32px;">
          <h1 style="margin: 0; font-size: 28px; font-weight: 700; letter-spacing: -0.025em; color: #ffffff;">⚠️ Capacity Alert</h1>
          <p style="margin: 8px 0 0 0; font-size: 16px; color: #e2e8f0; opacity: 0.9;">Room type is running low on availability (< 20%)!</p>
        </div>

        <!-- Alert Details Card -->
        <div style="background: rgba(15, 23, 42, 0.5); border: 1px solid rgba(255, 255, 255, 0.05); border-radius: 16px; padding: 24px; margin-bottom: 32px;">
          <h3 style="margin-top: 0; color: #f97316; font-size: 14px; text-transform: uppercase; letter-spacing: 0.1em; font-weight: 600;">System Audit Details</h3>
          
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.08);">
              <td style="padding: 12px 0; color: #94a3b8;">Hotel ID:</td>
              <td style="padding: 12px 0; text-align: right; color: #f8fafc; font-weight: 600;">#${rt.hotel_id}</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.08);">
              <td style="padding: 12px 0; color: #94a3b8;">Room Type ID:</td>
              <td style="padding: 12px 0; text-align: right; color: #f8fafc; font-weight: 600;">#${rt.id}</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255, 255, 255, 0.08);">
              <td style="padding: 12px 0; color: #94a3b8;">Time Window:</td>
              <td style="padding: 12px 0; text-align: right; color: #f8fafc; font-weight: 600;">Next 30 Days</td>
            </tr>
            <tr>
              <td style="padding: 16px 0 0 0; color: #94a3b8; font-size: 16px; font-weight: 600;">Availability Status:</td>
              <td style="padding: 16px 0 0 0; text-align: right; color: #ef4444; font-size: 18px; font-weight: 700;">&lt; 20% Remaining</td>
            </tr>
          </table>
        </div>

        <!-- Action Button -->
        <div style="text-align: center; margin-bottom: 32px;">
          <a href="${process.env.BASE_URL || 'http://localhost:5173'}/admin" style="display: inline-block; background: linear-gradient(135deg, #ef4444 0%, #f97316 100%); color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 12px; font-weight: 600; font-size: 16px; box-shadow: 0 4px 14px rgba(239, 68, 68, 0.4);">
            Manage All Inventory
          </a>
        </div>

        <!-- Footer -->
        <div style="border-top: 1px solid rgba(255, 255, 255, 0.08); padding-top: 24px; text-align: center; font-size: 12px; color: #64748b;">
          <p style="margin: 0 0 8px 0;">This email is an automated alert generated by Hotello Capacity Audit System.</p>
          <p style="margin: 0;">&copy; 2026 Hotello Inc. All rights reserved.</p>
        </div>
      </div>
    </div>
  `;

  try {
    const { data, error } = await resend.emails.send({
      from: fromEmail,
      to: adminEmail,
      subject: `⚠️ Capacity Warning: Hotello Inventory Low`,
      html: htmlContent
    });

    if (error) {
      console.error(`[SERVERLESS CAPACITY ERROR] Resend rejected dispatch to ${adminEmail}:`, error);
    } else {
      console.log(`[SERVERLESS CAPACITY SENT] Successfully sent capacity warning to ${adminEmail} using Resend! ID: ${data?.id}`);
    }
  } catch (err) {
    console.error(`[SERVERLESS CAPACITY ERROR] Direct error while sending capacity warning to ${adminEmail}:`, err.message);
  }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // Verify CRON Secret from Azure Logic Apps
  const cronSecret = req.headers['x-cron-secret'];
  if (cronSecret !== process.env.CRON_SECRET) {
      return res.status(401).json({ error: 'Unauthorized CRON trigger' });
  }

  try {
    // 1. Get all room types and their total capacities
    const { data: roomTypes, error: rtError } = await supabase
        .from('room_types')
        .select('id, hotel_id, total_rooms, hotels(admin_id)');
    
    if (rtError) throw rtError;

    // 2. Get reservations for the next 30 days
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const nextMonth = new Date(today);
    nextMonth.setDate(nextMonth.getDate() + 30);

    const { data: reservations, error: resError } = await supabase
        .from('reservations')
        .select('*')
        .eq('status', 'confirmed')
        .lt('check_in', nextMonth.toISOString().split('T')[0])
        .gt('check_out', today.toISOString().split('T')[0]);

    if (resError) throw resError;

    const notificationsSent = [];

    // Helper to calculate reserved nights falling within the 30-day window
    const getReservedDaysInWindow = (checkInStr, checkOutStr, startWindow, endWindow) => {
        let checkIn = new Date(checkInStr);
        let checkOut = new Date(checkOutStr);
        let start = checkIn < startWindow ? startWindow : checkIn;
        let end = checkOut > endWindow ? endWindow : checkOut;
        if (start >= end) return 0;
        return Math.ceil((end - start) / (1000 * 60 * 60 * 24));
    };

    // 3. Calculate capacity day-by-day
    for (const rt of roomTypes) {
        const rtReservations = reservations.filter(r => r.room_type_id === rt.id);
        const totalPossibleRoomNights = rt.total_rooms * 30; // total capacity in the next 30 days
        
        let reservedRoomNights = 0;
        for (const resv of rtReservations) {
            reservedRoomNights += getReservedDaysInWindow(resv.check_in, resv.check_out, today, nextMonth);
        }

        const currentlyAvailableRoomNights = totalPossibleRoomNights - reservedRoomNights;
        const availabilityPercentage = (currentlyAvailableRoomNights / totalPossibleRoomNights) * 100;

        // If availability is below 20%, trigger notification
        if (availabilityPercentage < 20) {
            // Find admin email
            const { data: adminProfile } = await supabase
                .from('user_profiles')
                .select('email')
                .eq('id', rt.hotels.admin_id)
                .single();

            if (adminProfile?.email) {
                await sendCapacityAlertEmail(adminProfile.email, rt);
                notificationsSent.push({ hotelId: rt.hotel_id, email: adminProfile.email });
            }
        }
    }

    return res.status(200).json({ success: true, processed: roomTypes.length, notificationsSent });

  } catch (error) {
    console.error('Capacity check error:', error);
    return res.status(500).json({ error: error.message });
  }
}
